### ISSUE TITLE
Create new tables in the database

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#10]
# What
We need to create new tables in the database so that we can store all the data of a responsible declaration and supplementary information. And add some fields and relations to the existing data model.

# How
![captura de pantalla 2017-11-21 a las 19 07 08](https://user-images.githubusercontent.com/16189/33088895-4719205a-ceef-11e7-92d2-85e03bcd9e99.png)
![captura de pantalla 2017-11-21 a las 19 06 47](https://user-images.githubusercontent.com/16189/33088898-4a8f439a-ceef-11e7-908a-1b5ba2d0f62a.png)

**Comment by rfuentesm2c** [comment]
I'll work on this!

**Comment by Senen** [comment]
Hi everybody! We are currently changing model and attributes because of latests changes from customer.

**Comment by Senen** [comment]
Merged via #23.
