### ISSUE TITLE
Open Data: enable a url with the lobby organizations and events

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#106]
# What
The client has requested the generation of a file with all the information of the lobby organizations and events.
This file must be generated once a day and accessible on the route we see fit.
I understand that we will be able to cache it so that the query is not done every time.

Example:
https://decide.madrid.es/system/api/proposals.csv
https://decide.madrid.es/system/api/debates.csv
https://decide.madrid.es/system/api/comments.csv

# How
We can based on: https://github.com/AyuntamientoMadrid/agendas/blob/master/lib/tasks/export.rake#L14

**Comment by iagirre** [comment]
I'll do it.

**Comment by taitus** [comment]
Close issue. Related #145
