### ISSUE TITLE
Organization user can cancel an event

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#111]
# What 
Organization user (lobby) can cancel a event until the date :scheduled
We have to allow the user to put a reason for the cancellation.
**Note:**
Managers are users with role :user. Those users who can manage holder agendas.

# How
- Add cancel button to edit page to update status to canceled.
- Send email to Manager user.
- The reason for cancellation must be saved in the Event field :reason (Pending approval)

**Comment by rfuentesm2c** [comment]
I'll do this one

**Comment by taitus** [comment]
Close issue. Related PR #125
