### ISSUE TITLE
Import organizations from asociations and federations CSV

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#13]
What
====
Import Organizations from CSV file.

- [ ] Create rake task, and spec for rake task with dummy file (check `spec/lib/tasks/db_rake_spec.rb`)
- [ ] Specify each attribute validations on plain text to notify data retrievers & provide csv dummy file as example

Columns to import
==============
Following CSV columns should be imported:

* Tipo Entidad -> entity_type
   Source file defines the value. When importing association this attribute should be :association. When importing association this attribute should be :federation
* Num. Inscripción: -> inscription_reference
* Razón Social-> name
* Tipo Vía -> address_type
* Calle -> address
* Número -> address_type
* Aproximación -> approach
* Cod. Postal -> postal_code
* Población -> town
* CIF -> identifier
* Fecha Registro -> inscription_date
* Primer Telf. -> phones
* Email -> email
* Internet -> web
* Distrito (para asociaciones) -> district
* Barrio (para asociaciones) -> neighbourhood
* Categoría -> category_id (findBy :name  🤔 )
* Ámbito -> scope
* Num. Socios (only for federations) -> members_count
* Asoc. Totales (only for asociations) -> associations_count

**Comment by Senen** [comment]
@bertocq Here is the source of CSV files to import:

* **Asociations**: http://datos.madrid.es/sites/v/index.jsp?vgnextoid=5628ae43b6d85410VgnVCM100000333a5a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD

* **Federations**: http://datos.madrid.es/sites/v/index.jsp?vgnextoid=b6f3532315dd3410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD

Customer want all columns from both files until Q column. These columns are:
PK | NOMBRE | DESCRIPCION-ENTIDAD | HORARIO | EQUIPAMIENTO | TRANSPORTE | DESCRIPCION | ACCESIBILIDAD | CONTENT-URL | NOMBRE-VIA | CLASE-VIAL | TIPO-NUM | NUM | PLANTA | PUERTA | ESCALERAS | ORIENTACION

So we need to create new columns to store all this information, or renegotiate data to store with customer.

**Comment by rfuentesm2c** [comment]
I'll do this one :)

**Comment by rfuentesm2c** [comment]
I'll do this one :)

**Comment by taitus** [comment]
Close issue. Related PR #97
