### ISSUE TITLE
New event: change select position_id

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#131]
# What
On the new event page need to be able to search for position_id (titular de agenda) by holders and by government area.

# How
I think getting this filter with a single field is very complicated. I propose to think of an alternative with two fields. One to search by government area an another to search by holders. to search by holders.
Any others suggestion?

**Comment by vicentemendozam** [comment]
I'll take this one

**Comment by taitus** [comment]
Close issue. Related PR #165
