### ISSUE TITLE
Lobby show

### ISSUE THREAD

**Issue by agileontheweb** [AyuntamientoMadrid/agendas#132]
# Where
Organization show

# What
- [x] Create the lobby page with the style of this site
https://rgi.cnmc.es/gruposdeinteres/anfac-asociacion-espanola-de-fabricantes-de-automoviles-y-camiones
- [x] Change text "Página pública de la Organización" with Lobby name
- [x] Change "Referencia" with "Número de anotación en registro"
- [x] Remove legal_representant and contact person
- [x] Change "Agentes" with "Personas que se reúnen"
- [x] Area of ​​interest: one below the other.
- [x] Change data format -   "dd-mm-aaaa"
- [x] Added state active, canceled 
- [ ] Disabled not work ... i put the label but with the  "Organization.validated.find" generate an error
    set_organizationapp/controllers/organizations_controller.rb
   def set_organization
      @organization = Organization.validated.find(params[:id])
    end

If i remove  "validated" this work.
So if i try this, it works

   def set_organization
      @organization = Organization.find(params[:id])
    end

- [x] Added icons + and - in accordion
- [x] Added message if not have result into accordion
- [x] Translate some text
- [x] * * Added login button in the header

# How
Use foundation accordion.

# Screen
**Accordion**
![captura de pantalla 2017-12-11 a las 14 27 25](https://user-images.githubusercontent.com/1497150/33833293-767e50c8-de7f-11e7-987f-5382bdf0000d.png)

**When there are no results**
![captura de pantalla 2017-12-11 a las 14 28 24](https://user-images.githubusercontent.com/1497150/33833326-93017e8c-de7f-11e7-9fb8-605b12ae8056.png)

**When is invalidate**
![captura de pantalla 2017-12-11 a las 14 33 10](https://user-images.githubusercontent.com/1497150/33833556-4a16cd70-de80-11e7-8f27-84403cb1e034.png)

Test
====
Fix manual test.
@taitus i passed test but you can see if they are well done.?! Thanks

Deployment
==========
Nothing to comment

Warnings
========
Nothing to comment

**Comment by agileontheweb** [comment]
@taitus you can check before doing a pull request.
Thanks

**Comment by taitus** [comment]
Close issue. Related #147
