### ISSUE TITLE
Manage user can set status event

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#133]
# What
Manager user can edit an event.

**Note:**
Managers are users with role :user. Those users who can manage holder agendas.

# How
- Manager user can edit an event status to "Accept". Send email to lobby user.
- Manager user can edit an event status to "Declined". The reason for Declined must be saved in the Event field :reason

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by taitus** [comment]
Close issue. Related PR #158
