### ISSUE TITLE
Public organization new search: by Agents

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#135]
# What
The customer want to be able search by agents.

# How
On searcher from public organization page we must be able to search by agents.
Add new value on searchable.
The search engine only has to return agents from "active organizations".
"active organizations": Organizations without "canceled_at" or Organizations with invalidate != true

**Comment by iagirre** [comment]
I'll do this one.

**Comment by taitus** [comment]
Close issue. Related PR #154
