### ISSUE TITLE
Public organization new orders: by alphabetical order 

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#139]
# What
New order by alphabetical order ASC/DESC
Now we have order by inscription date DESC, we need too by inscription_date ASC

**Comment by aitbw** [comment]
The default Organizations#index order is `inscription_date ASC`, unless you want an explicit filter on the drop down list, maybe?

I'm kinda confused with this requirement: It says we need sorting by alphabetical order but we need to add `inscription_date ASC`, could you clarify a little bit on this one, @taitus?

**Comment by taitus** [comment]
Hi @aitbw,
"New order by alphabetical order ASC/DESC" -->  refers to adding the possibility of alphabetically sorting in ascending and descending order on an explicit filter in the drop down list.

"Now we have order by inscription date DESC, we need too by inscription_date ASC" --> This requirement could be on another issue. But I decided to add it to this one. Simply ask that if there is now a filter by inscription_date ASC, add a filter by inscription_date DESC.

Ask me if you need any more information.

**Comment by aitbw** [comment]
That'll do. I'm going in with this one.

**Comment by taitus** [comment]
Close issue. Related PR #155
