### ISSUE TITLE
Event index (Public and Private): lobbies filter

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#14]
# What

Add a filter just to show "Events" with lobby activity.

# How

- [x] Add new filter on index "Events" by lobby_activity fields
  - [x] events#index
  - [ ] visitors#index

**Comment by rfuentesm2c** [comment]
I'll do this one :)

**Comment by vicentemendozam** [comment]
I'll take this one.

**Comment by taitus** [comment]
Close issue. Related PR #100
