### ISSUE TITLE
Change titles

### ISSUE THREAD

**Issue by agileontheweb** [AyuntamientoMadrid/agendas#148]
# What
Change  "Consulta del registro de Organizaciones" with "Consulta del registro de lobbies
Change "Últimas Organizaciones registradas" with "Incorporaciones más recientes" only when entering. Remove the text once the filter is used.

# How
Change yml.
On submit check if params :interests exist hide text."

# Screen
**On enter**
![captura de pantalla 2017-12-11 a las 16 22 42](https://user-images.githubusercontent.com/1497150/33838345-9a821422-de8f-11e7-979b-32fe8ad5dd78.png)

**On click submit**
![captura de pantalla 2017-12-11 a las 16 22 51](https://user-images.githubusercontent.com/1497150/33838361-a854f056-de8f-11e7-8b6e-323565a06cc2.png)

**Comment by taitus** [comment]
Close issue. Related PR #150
