### ISSUE TITLE
Public organizations index: lobbies filter

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#15]
# Where
* Depends on #17 

# What
Add a filter just to show organizations that have registered as "Lobbies".

# How

- [ ] Add new filter on index "Organizations" by references fields

Those with a reference have been registered as lobbies and those without a reference are Associations or Federations not yet registered as lobbies.

Screenshots
=========
Add

**Comment by rfuentesm2c** [comment]
I'll do this one

**Comment by taitus** [comment]
Close issue. Related PR #94
