### ISSUE TITLE
Public organizations index: export to csv, xls and json

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#16]
# What

Make an url accessible where you can download a csv, xls and json with all organizations

# How
- [x] Display all records from Organization

We need to export the same information defined at: #36

**Comment by bertocq** [comment]
We've similar requirement on the transparency app, solved around https://github.com/wairbut-m2c/transparencia/blob/master/lib/profile_exporter.rb#L144-L176 just in case it helps

**Comment by rfuentesm2c** [comment]
I'll do that.

**Comment by taitus** [comment]
Hi @rfuentesm2c 
We have passed 2 more fields that we have to add to the export and have updated in issue #16:

- Display Legal representant
   * Nombres/Apellidos o Razon Social (legal_representant.fullname )

- Display User (Persona física de contacto)
   * Nombre/Apellidos (user.name)

Sorry for the inconvenience

**Comment by rfuentesm2c** [comment]
Don't worry, I'll add it in the next upload

**Comment by Senen** [comment]
Closed via #74
