### ISSUE TITLE
Set event status: accepted

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#161]
# What
1. When user admin and user manager create a new event the status is :accepted
2. When user lobby create a new event an user manager/admin can change event status to :accepted 

# How
1. Add callback model or method controller for update status to :accepted when current_user have role :admin or role:user.
2. When a user with role :lobby create a new event, an user with role :admin or role :user can update event status to :accepted on edit event page. 
3. Email 6 (related issue #162 ): When user with role :admin or role :user accept an event, we need send email to "lobby"

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by taitus** [comment]
Close issue. Related PR #182
