### ISSUE TITLE
Check emails

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#162]
# What
Check when each email is sent to the application and its recipients

# How
- Email 1: When user with role :lobby create a new event, we need send email to "titular de agenda
- Email 2: When user with role :lobby cancel an event, we need send email to "titular de agenda"
- Email 3: When user with role :admin or role :user cancel an event, we need send email to "lobby"
- Email 4: When user with role :admin or role :user decline an event, we need send email to "lobby
- Email 5: When user with role :admin or role :user create an event, we need send email to "lobby"
- Email 6: When user with role :admin or role :user accept an event, we need send email to "lobby" (this feature will be implemented on #161 )

![captura de pantalla 2017-12-26 a las 14 27 21](https://user-images.githubusercontent.com/15726/34357634-fada5d9c-ea48-11e7-8b44-eec0480278dd.png)

* More information:
Por cierto, en el proceso de cancelación de una reunión, si es con actividad de Lobby y hay un lobby detrás, se tiene que mandar un email, pero si es una asociación/federación que no está registrado, no hay que mandar un e-mail. Y si cancelamos una reunión sin actividad de Lobby, tampoco hay que enviar un email.

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by Senen** [comment]
Closed via #210
