### ISSUE TITLE
Public organization index: Unify search engine

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#164]
# What
On public organization index we need unify search engine by keyword and by agents.
![captura de pantalla 2017-12-15 a las 10 56 37](https://user-images.githubusercontent.com/16189/34036898-fa3b24f4-e186-11e7-9b99-2a8abef34856.jpg)

# How
On search engine by keyword on organizations#index we need add search by agents. 
The search engine only has to return agents from "active organizations".
"active organizations": Organizations without "canceled_at" or Organizations with invalidate != true. This feature was implemented on PR #154 but an independent search input.  
We can check PR #154.

**Comment by vicentemendozam** [comment]
I'will take this

**Comment by taitus** [comment]
Close issue. Related PR #167
