### ISSUE TITLE
Agent: add new fields

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#168]
# What
When a lobby add a new Agent need check new field to allow that his information to be public. A lobby need attach a file when add new Agent.

# How
- Add new field "allow_public_data:boolean" on Agent model: "Acredito el consentimiento expreso de esta persona para que sus datos meramente identificativos puedan hacerse públicos"
- Add new relation between Attachment and Agents to allow attach a file when a Lobby user create new Agent: "fichero de acreditación". An Agent only have one attachment.
- Add allow_public_data and attachment file on page "new organization". Its same page that "add new Agent"
- allow_public_data and attach file as mandatory.

**Comment by Senen** [comment]
Closed via #218
