### ISSUE TITLE
Public organizations index

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#17]
# What

Show a paged listing with all organization records on a public page.
Any user can access to this index, including not logged ones.

# How
- [ ] Add new index from Organizations.

I think it would be nice to have two separate controllers for organizations, one for admin section and another for public pages like **organizations#index** and organizations#show.

Screenshots
=========
![public-organizations-index](https://user-images.githubusercontent.com/1497150/33100692-a4b7f562-cf15-11e7-9e2f-3b5b2c880935.jpg)

**Comment by Senen** [comment]
I'm on it!

**Comment by taitus** [comment]
Close issue. PR related #79
