### ISSUE TITLE
Cron: Rake tasks

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#170]
# What

There is three tasks we want to run periodically:

**Run on each server**
Next task should be runned on each server because they are not using shared filesystem for now.
We want to run this tasks once per day.

1. rake export:organizations 
2. rake export:agendas

**Run on one server**
Next importation task should be runned on only one server because they update a shared resource, the database.

3. rake import_organizations:parse_associations
4. rake import_organizations:parse_associations
5. rake events:update_event_status
6. rake madrid:import

# How
Alternatives to implement Cron jobs:
Consul use:  http://github.com/javan/whenever
Other gems: https://github.com/ondrejbartas/sidekiq-cron (need sidekiq)

**Comment by Senen** [comment]
Closed via #346
