### ISSUE TITLE
Production: Check open data links from Events and Organizations

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#171]
# What
The rake task currently generates open data files in the "public/export" folder. In local works correctly, in heroku: staging we can't write to that folder.

**Comment by raul-fuentes** [comment]
It seems heroku does not save files, it would be advisable to use some other service to save them

**Comment by Senen** [comment]
Close this issue because we are not using heroku server anymore, we are using preproduction Madrid server where we can write at public folder.
