### ISSUE TITLE
Wrong events index title

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#178]
# What
Events public index page has wrong title

# How
Replace title with original one  "Agendas públicas"

# Screenshot
![captura de pantalla 2017-12-18 a las 13 59 25](https://user-images.githubusercontent.com/15726/34107350-34008a54-e3fc-11e7-96c5-2ad52100be37.png)

**Comment by agileontheweb** [comment]
In pull request #180

**Comment by taitus** [comment]
Close issue. Related PR #180
