### ISSUE TITLE
Home: Add new buttons

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#18]
# Where
* Depends_on: #17

# What
In this first version actual home should have a few links to allow users to access other important public pages.In next versión we will create a welcome#home page with links to many other pages. See #27 to check @agileontheweb first proposal.

Add links to access the "Agendas públicas" and the "Consulta del registro".

# How

 - [ ] Link to "consulta del registro"
 - [ ] Link to "Agendas públicas" (Current Home)

# Screenshot
![agenda-publica](https://user-images.githubusercontent.com/1497150/33132809-f9033eda-cf9a-11e7-989e-5f495a2be79e.jpg)

**Comment by Senen** [comment]
@agileontheweb here you have this issue waiting for you 🇮🇹 💪

**Comment by Senen** [comment]
Closed via #82. 👍
