### ISSUE TITLE
Manager User: add new index with default filters

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#181]
# What
Current version:
A logged user manager (role: user) have an index called "Solicitud de eventos" where all events with any status are displayed. [requested, accepted, done, rejected, cancel].

New version:
A logged user manager (role: user) will have 2 index:
- "Bandeja de solicitudes": Display events with status [:requested, :rejected] by default and with activity_lobby: true
- "Eventos": Display events with status [:accepted, :done, :cancel] by default. On this page not need add filter activity_lobby by default.

In both indexes we have to keep the "search by state" and the checkbox "Lobby activity" that currently exists.

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by taitus** [comment]
Close issue via #190
