### ISSUE TITLE
Admin event new

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#20]
# What

An "administrator/calendar manager" can create a new event.

# How

- [ ] Add new fields to the current form to create a event.

# Screenshot

**First version. Waiting for your answer.**

![new-events](https://user-images.githubusercontent.com/1497150/33319801-3ddad546-d440-11e7-8427-c4b33180f8e9.jpg)

**Comment by taitus** [comment]
CAMPOS PARA LA GESTIÓN DE UNA REUNIÓN

1. Título de la reunión
2. Lugar
3. Descripción
4. Fecha
5. Titular de la agenda
6. Asistentes titulares de agenda
7. Otros asistentes
8. Archivos adjuntos

Nueva estructura de la ficha para definir un evento
1. Título de la reunión (obligatorio)
2. Lugar (obligatorio)
3. Descripción (obligatorio)
4. Fecha (obligatorio)
5. Titular de la agenda (obligatorio)
6. Asistentes titulares de agenda (opcional)
7. ¿Es una reunión donde se hará actividad de Lobby? S/N. Se mostrará en blanco, y
tendrá que elegir entre SI o NO. (obligatorio)
8. Si es actividad de Lobby ***
9. Si NO es actividad de Lobby:
a. Otros asistentes (de 0 a n)
b. Archivos adjuntos (de 0 a n)
i. Documento: obligatorio
ii. Descripción: opcional

10. Fecha en la cual el evento se verá en la página web pública: Es un campo obligatorio,
y por defecto será la fecha en la cual se graba el evento, y no puede ser nunca superior
en más de 15 días a la fecha de celebración del evento.

------------------------------------------------------------------------------------------
# 8. Si es actividad de Lobby ***
a. Lobby (1)
b. Inscrito en: (6)
c. Categoría (lo trae directamente del registro, no hay que rellenarlo)
d. Empresa/s que representa (2)
e. Personas que asistirán (dadas de alta asociadas al Lobby) (3)
f. Otros asistentes (4)
g. Archivos adjuntos: (5)

Por lo menos debe haber un Lobby seleccionado.
(1), debe dar opción a buscar en una pantalla auxiliar por texto y/o por NIF, y
añadir el Lobby que se selecciona. En esa pantalla auxiliar, debe mostrar un
listado de lobbies y de entidades inscritas en el registro municipal de entidades
ciudadanas, y nos debe poder permitir filtrar por texto y/o NIF y/o incluir o no
entidades ciudadanas. En esa pantalla se podrá seleccionar el lobby, y
arrastrará la selección a la página principal.
Si se selecciona una asociación, que está en el registro de entidades y también
en el registro de lobbies, debe arrastrar los datos del registro de lobbies.

(2) Una vez seleccionado el lobby, nos debe permitir seleccionar a la empresa
o persona que representa. Lógicamente, si solo representa a una empresa o a
sí misma, saldrá en ese campo Persona o Entidad Representada, a sí misma.
Si representa a varias, nos debe salir una ventana con opción a seleccionar de
1 a n empresas/personas. Obligatorio, ya porque se seleccione o porque solo
hay un valor posible.

(3) Asociado al Lobby, hay personas que se reunirán. Previamente la persona
de contacto del Lobby, el cual tiene el usuario y contraseña de la aplicación, ha
tenido que dar de alta a dichas personas.
Igualmente, si solo hay 1 persona dada de alta, automáticamente lo arrastrará
sin necesidad de seleccionarlo.
Si no existe ninguna persona DUDA.
Si la reunión es con una asociación, no hay persona asociada, con lo cual, no
sería obligatorio este campo. DUDA.

(4) Igual que actualmente, se pueden dar de alta otras personas para asistir a
la reunión. Estas personas no se tienen que dar de alta previamente en la
aplicación de lobbies. (De 0 a n)

(5) Archivos adjuntos: Puede haber de 0 a n archivos, y cada uno tendrá estos
campos, siendo obligatorio el documento, y el campo si es o no público.
iv. Documento: obligatorio
v. Descripción: opcional
vi. ¿Es público? (S/N): obligatorio. Saldrá en blanco y se tendrá
que seleccionar.
Asociados a estas opciones anteriores, tendremos los botones de añadir,
modificar y eliminar, cuando corresponda.

(6) “Inscrito en”, es un campo que saldrá automáticamente y que nos
indicará, si la entidad o persona con la que nos reunimos y que va a hacer
de Lobby, está inscrita como Lobby, como Entidad o como ambos.

**Comment by vicentemendozam** [comment]
I'll take this one.

**Comment by taitus** [comment]
Close issue. PR related #102
