### ISSUE TITLE
Create welcome email to organization user

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#21]
# What

Once you have registered a new organization, we need to send an email to the organization user so they can access the application to request an "Event".

# How
We only need UserMailer and welcome view for now. Later we will send email in another PR.

- [ ] UserMailer with welcome action.
- [ ]  user_mailer/welcome.html.erb

Example:
"Bienvenido #{user.name}, Acabas de registrarte en el registro de lobbies. Con el usuario: #{user.email} y el passwore #{user.password} podrás solicitar reuniones para hacer lobby."

**Comment by iagirre** [comment]
I'll do this.
