### ISSUE TITLE
Website map

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#212]
What
=====
Create sitemap page with following links.

Create page at /websitemap.

**Mapa Web**

- Portada: Link to root path.
- Agenda: Link /visitors
- Registro de lobbies Link to registration_lobbies/index
  - Consulta del registro
  - Alta y baja
  - Código de conducta, sanciones y normativa
  - Preguntas Frecuentes
  - Estadísticas
  - Buzón de incumplimientos
-Huella normativa (edited)

How
====
Creating new static page to render sitemap links.

Screenshot
========
Pending

**Comment by vicentemendozam** [comment]
I'll take this one.

**Comment by Senen** [comment]
Thanks @vicentemendozam! 👍

**Comment by Senen** [comment]
Closed via #220
