### ISSUE TITLE
Admin organization new

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/agendas#22]
# What

We want an administrator to be able to register Organizations(associations and lobbies) in our application.

# How

- [ ] Storing all information from the "responsible declaration" and the "supplementary information".
- [ ] Create the user associated with an Organization. The data to create this user will be collected from the registration form in the section "Persona física de contacto".

We do not want to send welcome email to this organization user yet. This feature will be available at next version.

# Screenshot
![new-organization-form](https://user-images.githubusercontent.com/1497150/33134415-f811c136-cf9f-11e7-9d6a-51ed1779cee9.jpg)

**Comment by taitus** [comment]
Close issue. PR Related #78
