### ISSUE TITLE
FAQ: Frequently asked questions

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#25]
What
====
Allow administrators to create FAQ entries

HOW
====
* Creating a a new public page to render all questions and answers
* Creating a new table questions with following fields:
  * title:string
  * text:answer
  * position: integer 
* Only administrators (users with role :admin) can manage FAQ page.
* Position attribute allow administrators to define questions order at public FAQ page.
* Create full managment of questions on admin area

Screenshots
=========
**Admin - listing questions**

![listado-preguntas-frecuentes](https://user-images.githubusercontent.com/1497150/33098639-64c87e4c-cf0e-11e7-85d4-4cc095fdf0ee.jpg)

**Admin - New question**

![nueva-pregunta](https://user-images.githubusercontent.com/1497150/33098642-67eed45e-cf0e-11e7-84be-aab37fa2a113.jpg)

**Frontend: - Listing questions**

![faq](https://user-images.githubusercontent.com/1497150/33091299-fe932350-cef6-11e7-864e-2e67fb81b830.jpg)

**Comment by bertocq** [comment]
About the reordering, @iagirre did some cool tricks at consul https://github.com/consul/consul/pull/2037 to do this with drag&drop, but if up and down arrows are easier... go for it, on the technical side of requirements, take a peak at involved code as we try to enforce that all orderable items will have a value for the "position" attribute at all times, and values will be consecutive and start from `1`

**Comment by Senen** [comment]
@bertocq you are totally right, drag and drop is the cleanest solution! With consul example it should be easier

**Comment by iagirre** [comment]
I'll go with this.

**Comment by taitus** [comment]
Close issue. Related #88
