### ISSUE TITLE
Final home page

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#27]
Where
=====
* Depends on a lot of another features.  We leave this task for the latests.

What
====
Build new home page like with links to everywhere 

Screenshots 1 version
=========
![home](https://user-images.githubusercontent.com/1497150/33099260-9201b1f6-cf10-11e7-89ac-292c45477762.jpg)

**Open menu**
![home-open-menu](https://user-images.githubusercontent.com/1497150/33099495-5489adaa-cf11-11e7-9830-35a7a336fb68.jpg)

**Idea Responsive**
When is responsive smaller text Gobierno abierto trasparencia.
![captura de pantalla 2017-11-21 a las 23 13 27](https://user-images.githubusercontent.com/1497150/33099584-a172cfd4-cf11-11e7-8f32-94faefd438da.png)

Screenshots 2 version (with modifications)
=========
**inicio**
![home](https://user-images.githubusercontent.com/1497150/33945099-55e381f8-e01e-11e7-84b1-057a973c137d.png)
**Agendas**
![agendas_new](https://user-images.githubusercontent.com/1497150/33945097-55ba1412-e01e-11e7-8bb5-e229872a4e85.png)
**Registro**
![registrodelobbi](https://user-images.githubusercontent.com/1497150/33945096-55786fc6-e01e-11e7-81c7-dbeb0a8495ee.png)
**Filters with labels**
![filtros](https://user-images.githubusercontent.com/1497150/33945095-55567452-e01e-11e7-9f88-16bd7e9b1dad.png)

**Comment by Senen** [comment]
@agileontheweb can you attach your new home proposal for final version?

**Comment by taitus** [comment]
Close issue via #163 #82
