### ISSUE TITLE
Admin organizations index

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#28]
What
====
Administrator users can access to admin/organizations#index

How
====
Create admin/organizations#index controller and action.
Create paginated index view.
Only administrator users should be able to view this page.

Screenshots
=========
![organiz-list](https://user-images.githubusercontent.com/1497150/33097323-0bebe4ac-cf0a-11e7-9f0e-734a34d60f60.jpg)

**Comment by iagirre** [comment]
I'll do this.

**Comment by Senen** [comment]
Closed via #76! Thanks @iagirre
