### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#281]
What
====
Create a statistics page.

This page is currently created and empty at: **"/statistics"**.

* **Per category lobbies**: Number of active lobbies per category (ver ejemplo de la CNMC)
* **Per interest lobbies**: Number of lobbies per interest

* **Inscribed lobbies**: Amount of active lobbies inscribed
  * **Amount of self employed lobbies** (Lobbies por cuenta propia)
  * **Employee Lobbies** (Lobbies por cuenta ajena)
  * **Personas inscritas para reunirse**: Cantidad de agentes activos

* **Lobby events**: Amount of events with lobby activity
* **Total events**: Amount of events
* **Amount of public agendas**: Total amount of holders.

La fecha a tomar de referencia será el 28/12/2017 para las extracciones de información.

**Comment by Senen** [comment]
There is a information organization sample provided by the customer:
![captura de pantalla 2018-01-02 a las 17 00 58](https://user-images.githubusercontent.com/15726/34490006-a5cc9f40-efde-11e7-943c-8dce5aed673f.png)

And some useful examples from customer:
* http://ec.europa.eu/transparencyregister/public/homePage.do?locale=es
* https://rgi.cnmc.es/

**Comment by vicentemendozam** [comment]
I'll take this one!

**Comment by Senen** [comment]
Closed via #298
