### ISSUE TITLE
Email notifications contents

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#283]
What
====
Check all email notifications recipients and content:

**Recipients**

Cod.Correo | Descripción | Para | CCO
-- | -- | -- | --
RL.S | Solicitud 			evento | Titular 			y Gestores | registrodelobbies@madrid.es
RL.A | Aceptación 			evento | Lobby | registrodelobbies@madrid.es
RL.R | Solicitud 			evento rechazada por Titular | Lobby | registrodelobbies@madrid.es
RL.CL | Solicitud 			evento cancelada por Lobby | Titular 			y Gestores | registrodelobbies@madrid.es
RL.CT | Solicitud 			evento cancelada por Titular | Lobby | registrodelobbies@madrid.es
RL.BI | Buzón 			de incumplimientos | BuzonLobby@madrid.es |  
RL.ALTA | Alta 			de Lobby | Lobby | registrodelobbies@madrid.es
RL.MOD | Modificación 			de Lobby | Lobby | registrodelobbies@madrid.es
RL.BAJA | Baja 			de Lobby | Lobby | registrodelobbies@madrid.es
RL.IN | Inhabilitación 			de Lobby 			(No 			hay que implementar este correo) |   |  

**Contents**
[Emails_V2.pdf](https://github.com/AyuntamientoMadrid/agendas/files/1598055/Emails_V2.pdf)

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by raul-fuentes** [comment]
Should I wait for https://github.com/AyuntamientoMadrid/agendas/issues/282 ?

**Comment by Senen** [comment]
Hi @raul-fuentes, i think we can start doing it without waiting for #282 to be finished, you should completely ignore styles, header and footer defined on "Emails_V2.pdf" file. Later @agileontheweb will merge #282 in your PR and finalize it!

Try to use basic HTML elements like <p>, <ul>, <ol>, <table> to create email contents ...

**Comment by Senen** [comment]
Hi @raul-fuentes, #282 was merged through #290! Maybe you can rebase your current branch with master latest version!

**Comment by vicentemendozam** [comment]
I'll take this one

**Comment by Senen** [comment]
Closed via #332
