### ISSUE TITLE
Admin organizations edit: Invalidate organization

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#29]
# What
An admin user can invalidate a Organization

# How
- [ ] Add new field on Organization invalidate:boolean
- [ ] Only display Organizations with "invalidate: false" on public organization index.

# Screenshots
![editar-organizacion](https://user-images.githubusercontent.com/1497150/33134497-2ae3622c-cfa0-11e7-8f37-0fd1f09c60a7.jpg)

**Comment by rfuentesm2c** [comment]
I'll do this one :)

**Comment by rfuentesm2c** [comment]
I'll wait until more instructions

**Comment by bertocq** [comment]
Doubt was resolved, button to "invalidate" needs to be at the bottom in red as the mockup displays
![screen shot 2017-11-29 at 20 54 28](https://user-images.githubusercontent.com/983242/33396063-bb50102e-d547-11e7-92c7-3691fc54bdf6.jpg)

**Comment by taitus** [comment]
Close issue. Related #99
