### ISSUE TITLE
Be a hero

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#300]
# What 
If you want to be a hero fix next deprecation warning. 😆 

It is very annoying to have to see this warning constantly in the local environment and when running specs.

# How
I tried and not succeed! 😢 

**Here you have annoying sample**
➜  agendas git:(new-statistics-page-refactor) rspec spec                                     
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.

Randomized with seed 22352
..DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
......................................DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.......DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.....DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
........................................................................Sunspot server took 1.01 seconds to start
...............................**........**.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
......................................DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from block (4 levels) in <top (required)> at /Users/sendero/dev/railsworkspace/agendas/spec/features/admin/events_spec.rb:46)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from block (4 levels) in <top (required)> at /Users/sendero/dev/railsworkspace/agendas/spec/features/admin/events_spec.rb:16)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from block (4 levels) in <top (required)> at /Users/sendero/dev/railsworkspace/agendas/spec/features/admin/events_spec.rb:78)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
.DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:21)
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from _app_views_layouts__admin_sidebar_html_erb__4081026005529087653_70362287474740 at /Users/sendero/dev/railsworkspace/agendas/app/views/layouts/_admin_sidebar.html.erb:59)
..................

**Comment by aitbw** [comment]
I'm on it.

**Comment by raul-fuentes** [comment]
Hi, the solution to this bug it's waiting in the PR https://github.com/AyuntamientoMadrid/agendas/pull/288 . Its caused by an string hash in helpers/admin/sidebar_helper.rb

**Comment by Senen** [comment]
Closed via #317
