### ISSUE TITLE
Infringements mailbox

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#31]
What
====
Create a page to allow any user to send an email anonymously to all administrator user.

How
=========
Send email with all collected data at contact form.

Contact form has the following data:
* subject
* description: wysiwyg
* link
* attachment

Warnings
=======
Since this page is publicly accessible ... do we need a captcha system?

Screenshots
=========
![buzon-de-incumplimientos-form](https://user-images.githubusercontent.com/1497150/33096402-2bbda912-cf07-11e7-8080-8e643d59262d.jpg)

**Comment by bertocq** [comment]
About the captcha question, at consul/consul we use [invisible_captcha](https://github.com/markets/invisible_captcha) gem

With `    <%= f.invisible_captcha :subtitle %>` at the form and `  invisible_captcha only: [:create, :update], honeypot: :subtitle` at the controller (being `subtitle` a fictional attribute not present on the model or database table)

Should that be enough @Senen ?

**Comment by iagirre** [comment]
I can do this.
