### ISSUE TITLE
Admin can remove organizations

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#32]
# Where
~~Depends on: #28 ~~

# What
We want an administrator to be able to "soft delete" Organizations

# How
- [ ] Add new field "canceled_at" to check this organization as deleted. This organization will continue to appear in the listings of our application.
- [ ] Delete User associated with organization. We can use gem 'paranoia' to make easier to soft_delete record . Other option is to use a custom field "deleted_at" to mark soft_deleted records.

**Comment by aitbw** [comment]
I'll gladly do this one, but I need some clarification regarding the 2nd point of the issue.

If I (soft) delete an organization, the user associated with it will be soft deleted as well? Or will it be removed completely from the DB?

**Comment by taitus** [comment]
@aitbw  First of all, apologize for the delay in answering.
With regard to deleting a user, I think we should do the same process as for organizations (soft-delete) so that we can always recover the old data.

**Comment by aitbw** [comment]
No worries, @taitus. Thanks for the response, I'll get on it immediately.
