### ISSUE TITLE
Admins can reset any other user password

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#33]
What
====
Allow administrator users to reset any user password.

How
====
Adding password and password_confirmation fields to user edit form into a separate fieldset "Reiniciar contraseña".

If password and password_comfirmation are not defined these fields should be ignored. If they are informed we have to validate both given passwords are equal.

Screenshots
=========
![modify-user](https://user-images.githubusercontent.com/1497150/33098814-eadded3c-cf0e-11e7-8470-059ff04fb5a7.jpg)

**Comment by aitbw** [comment]
I'm on it.

**Comment by taitus** [comment]
Close issue. Related #89
