### ISSUE TITLE
General static pages

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#34]
# What
Create following static pages:
- "Que es el Registro de Lobbies"
- "Normativa"
- "Código de conducta"
- "Protección de datos"
- "Apartados normativos y de documentación"

# How
- [x] Create for public static pages on pages_controller:
  - [x] pages_controller#about_lobbies
  - [x] pages_controller#rules
  - [x] pages_controller#conduct_code
  - [x] pages_controller#data_protection
  - [x] pages_controller#regulatory_and_documentation

**Comment by aitbw** [comment]
Is this issue ready to go, @taitus?

**Comment by taitus** [comment]
Hi @aitbw,
This morning I sent an email requesting information from each of these public static pages. 
You can take the issue and implement controller and views ready to add the information.

**Comment by taitus** [comment]
Close issue. Related PR waiting_for_customer #101
