### ISSUE TITLE
Public organizations index: sorting by created at DESC

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#35]
# Where
* Depends on #17 

# What
Add new sorting option by created at DESC to public organization index.

# How

- [ ] Add new order by created_at

Screenshots
=========
![public-organizations-index-at](https://user-images.githubusercontent.com/1497150/33100659-742e14e4-cf15-11e7-8f8f-3a438cae1e14.jpg)

**Comment by jvmendozamm2c** [comment]
I'll take this one.

**Comment by taitus** [comment]
Close issue. Related PR #96
