### ISSUE TITLE
Public organization show

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#36]
# What
Public page of an organization.

~~We are waiting for customer to get public information that can be published.~~

# How 
This page is publicly visible by everyone. Also this information is the same offered on CSV exportation process.

- Create a public action at organizations_controller to show public information of organizations.
- Display only this lobby public info:
   * Código de Lobby (organization.id)
   * NIF (organization.identifier)
   * Nombre/Apellidos o Razón Social (organization.fullname)
   * CP (organization.postal_code)
   * Domicilio (organization.address)
   * Municipio (organization.town)
   * Provincia (organization.province)
   * Categoría (organization.category_id)
   * Finalidad y objetivos (organization.description)
   * Web (organization.web)

- Display Legal representant
   * Nombres/Apellidos o Razon Social (legal_representant.fullname )

- Display User (Persona física de contacto)
   * Nombre/Apellidos (user.name)

- Display more lobby info (Datos de quien va a ejercer la actividad de lobby por cuenta propia)
   Many organization wont have this info defined.
   * Ejercicio anual (organization.fiscal_year)
   * Fondos dedicados a la actividad e lobby (organization.range_funds)
   * Ayudas y/o subvenciones recibidas del Ayto (organization.subvention)
   * Contratos y/o convenios con el Ayto (organization.contract)

- Display represented entities
   * NIF (represented_entity.idenfier)
   * Nombres/Apellidos o Razon Social (represented_entity.fullname )
   * Fecha de inicio de representación (represented_entity.from)
   * Fecha de final de representación (represented_entity.to)
   * Fondos que la entidad dedica (represented_entity.range_funds)
   * Ejercicio anual: (represented_entity.fiscal_year)
   * Ayudas y/o subvenciones recibidas del Ayto (represented_entity.subvention)
   * Contratos y/o convenios con el Ayto (represented_entity.contract)

- Display organization agents:
   * Nombre/Apellidos (agent.fullname)
   * Fecha de inicio de representación (agent.from)
   * Fecha de fin de representación (agent.to)

- Display organization interests:
   * Nombre (interest.name)

# Screenshot
![public-organization-show- 36](https://user-images.githubusercontent.com/1497150/33149066-8f53566c-cfce-11e7-9b15-b22cc236a7ea.jpg)

**Update screenshot**
![organization-update](https://user-images.githubusercontent.com/1497150/33184855-31a524f8-d07f-11e7-93cb-5c5c7841c4e5.jpg)

**Comment by Senen** [comment]
Hi @agileontheweb, i updated public information for lobbies. Whe have to hide some information of our initial screenshot proposal

**Comment by taitus** [comment]
@agileontheweb The branch is finished and tested by me. Now you just have to give your designer touch.

**Comment by Senen** [comment]
Closed via #84
