### ISSUE TITLE
Public organizations index: export to csv, xls and json (only not registered and acting as lobby)

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#37]
# Where
* Related issues: #16 

# What

Make an url accessible where you can download a csv, xls and json file only with not regitered organizations that have been assisted to any lobby event.

These link will be referenced from another platforms.

# How
Not registered associations are those who do not have attribute "reference" defined. One organization is acting as lobby when is an attendee of a lobby event or when an organization is the event requester.

**Comment by bertocq** [comment]
As commented at https://github.com/AyuntamientoMadrid/agendas/issues/16#issuecomment-346293651 I would use the same implementation to both issues (#16 and this one) and taking a look at transparency repo just in case we can reuse some code from there (if its clean obviously)

**Comment by rfuentesm2c** [comment]
I will continue with this one :)

**Comment by Senen** [comment]
Sorry @rfuentesm2c 🙏 , i forgot you are working here, i made a simple version of this issue using you code from #74.

**Comment by Senen** [comment]
Closed via #85. As @bertocq commented i have used PublicOrganizationExport.
