### ISSUE TITLE
Email: message content

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#375]
# What
Change message content on email.

# How
- Create:
  - Change "reference" to "lobby name" on email content. Ex: " Registro de Lobbies: alta de lobby MIS AMIGAS LAS PALOMAS"
- Destroy:
  -  Change subject "Alta de lobby" to "baja de lobby". Ex: "Registro de Lobbies: baja de lobby MIS AMIGAS LAS PALOMAS"
  - Add to body content "Su información seguirá siendo pública indicando la fecha de baja en el Registro"
- Edit:
  - Change "reference" to "lobby name" on email content.
  - Display "modification_date"
- Invalidated:
  - Change "reference" to "lobby name" on email content.

**Comment by Senen** [comment]
Closed via #379
