### ISSUE TITLE
User can edit their password 

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#38]
# What
Allow any logged user to change his password.

# How 
- [ ] Activating default devise/passwords#edit
- [ ] Adding a new administration menu link to go to password edit page.

# Screenshot
![password](https://user-images.githubusercontent.com/1497150/33102184-df032696-cf1b-11e7-9277-11fd68b563a8.jpg)

**Comment by iagirre** [comment]
I'll do this one.

**Comment by Senen** [comment]
Thx @iagirre! 🤗

**Comment by Senen** [comment]
Closed via #72
