### ISSUE TITLE
Lobbies static pages

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#39]
# What
Create following static pages:
- "New organization"
- "Edit organization"
- "Delete organization"

# How
- [x] Create for public static pages on pages_controller:
  - [x] pages_controller#new_organization
  - [x] pages_controller#edit_organization
  - [x] pages_controller#delete_organization
- [x] Add links(target: blank) on administration menu only for organizations users:
  - [x] to "edit_organization"
  - [x] to "delete_organization"

# Screenshot

**Edit**
![captura de pantalla 2017-11-22 a las 0 48 09](https://user-images.githubusercontent.com/1497150/33102831-ed41426c-cf1e-11e7-8c61-49adfe392af2.png)

**Delete**
![captura de pantalla 2017-11-22 a las 0 48 36](https://user-images.githubusercontent.com/1497150/33102830-ed25c17c-cf1e-11e7-8092-83a18facfeab.png)

**Register**
![alta-en-el-registro-de-lobbies](https://user-images.githubusercontent.com/1497150/33104930-09be78c2-cf2b-11e7-83a0-40f46851a779.jpg)

**Edit**
![modificacion-registro-de-lobbies](https://user-images.githubusercontent.com/1497150/33104929-099c4734-cf2b-11e7-91f1-9a7a7c5b914e.jpg)

**Delete**
![baja-en-el-registro-de-lobbies](https://user-images.githubusercontent.com/1497150/33104927-0965f968-cf2b-11e7-9737-a9973aeb104b.jpg)

**Comment by rfuentesm2c** [comment]
I'll do this one !
