### ISSUE TITLE
Production server is able to send emails?

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#42]
What
====
I cannot found any mail server configuration at production environment. I really start to think that this application is not sending any email for now.

**Comment by Senen** [comment]
@bertocq ¿can you help us asking IAM application maintainers for that information? 🙏

**Comment by bertocq** [comment]
I think @voodoorai2000 is the one with the contacts & knowledge about this

**Comment by voodoorai2000** [comment]
@Senen For the production servers inside IAM, you will only need to setup the email delivery method as :stmp. The rest of the configuration is dealt with by IAM at a scope outside of a Rails app.

For the staging environment in Heroku, feel free to use the addon that you are most comfortable with 😌

**Comment by Senen** [comment]
Mailer configuration was missing on preproduction and production files, see #199 changes.

To make it working on preproduction and production servers we had to manually add **server_name** entry to screts.yml file.
