### ISSUE TITLE
Manager and organization user event index

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#51]
# What
Manager and organizations user will be able to see a list of all their events and filter them by status.

# How
- [ ] Add filters on lists of events by status:
  - [x] Solicitada
  - [x] Aceptada (con cambios o sin cambios)
  - Realizada (No existe esta estado , pero se sbae con la siguiente condición: Aceptadas y event.date <= Date.current)
  - [x] Rechazada (implica determinar el motivo del rechazo)
  - [x] Cancelada por el usuario

**Comment by vicentemendozam** [comment]
I'll take this one.

**Comment by taitus** [comment]
Close issue. Related PR #146
