### ISSUE TITLE
Organization categories seeds

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#62]
What
====
We will need organization categories loaded on production database.

**Needed categories**
Consultoría profesional y despachos de abogados | Empresas | AsociacionesFundaciones |
Sindicatos y organizaciones profesionales | Organizaciones empresariales |
ONGs y plataformas sin personalidad jurídica | Universidades y centros de investigación |
Corporaciones de Derecho Público (colegios profesionales, cámaras oficiales, etc.) | Iglesia y otras confesiones | Otro tipo de sujetos.

How
===
Adding to the seeds file? Or maybe better to create a custom file and load it through a rake task?

**Comment by iagirre** [comment]
I'll do this.

**Comment by iagirre** [comment]
> Adding to the seeds file? Or maybe better to create a custom file and load it through a rake task?

How about both? Rake task for app in production and seeds for fresh instalations?

**Comment by Senen** [comment]
Closed via #80! 🍻
