### ISSUE TITLE
Organization interests seeds

### ISSUE THREAD

**Issue by taitus** [AyuntamientoMadrid/agendas#73]
What
====
We will need organization interests loaded on production database.

**Needed interests**
Actividad económica y empresarial
Actividad normativa y de regulación
Administración de personal y recursos humanos
Administración electrónica
Administración económica, financiera y tributaria de la Ciudad
Atención a la ciudadanía
Comercio
Consumo
Cultura (bibliotecas, archivos, museos, patrimonio histórico artístico, etc.)
Deportes
Desarrollo tecnológico
Educación y Juventud
Emergencias y seguridad
Empleo
Medio Ambiente
Medios de comunicación
Movilidad, transporte y aparcamientos
Salud
Servicios sociales
Transparencia y participación ciudadana
Turismo
Urbanismo
Vivienda

How
===
Adding to the seeds file? Or maybe better to create a custom file and load it through a rake task?

**Comment by iagirre** [comment]
I'll do this.

**Comment by Senen** [comment]
Closed via #81. Thx @iagirre 😄
